### ISSUE TITLE
Write qrcode png files to the component's folder

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10873]
This is a follow-up to https://github.com/mozilla/addons-frontend/pull/10855.

The utility to generate qr codes currently writes them to `dist`, but we'd like to eventually write them to a subfolder of the QRCode component. Once that component exists, and therefore the folder exists, we should change the utility to write the files to that folder.

**Comment by willdurand** [comment]
I think that has been fixed in https://github.com/mozilla/addons-frontend/pull/10904 or even before.

**Comment by bobsilverberg** [comment]
@willdurand The command-line util still writes the files to `dist`, and the `CopyPlugin` copies them from `src/amo/components/AddonQRCode/img`, so manual intervention is still required and therefore this is still an issue that needs to be fixed. We could simply change the util to write the files to `src/amo/components/AddonQRCode/img`, or perhaps there's another way to tie it all together? Should we make the generation of the files part of the build process?

**Comment by willdurand** [comment]
heh, ok. Yeah, we should change the path in the script.

**Comment by willdurand** [comment]
> Should we make the generation of the files part of the build process?

No. Using the `CopyPlugin` is fine.
