### ISSUE TITLE
If an addon is added to a collection from its details page, it will be displayed only after refreshing the collection page.

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5723]
Steps to reproduce:
1. Be sure that you already have a collection with some addons and that you already opened it at least one time
2.Open an addon details page and add the addon to the collection from Step1
3.Go to "View my collections" page and select the collection from Step1

Expected results:
The add-on added in Step2 is present inside collection

Actual results:
The add-on is displayed only after a page refresh

Please see a video with the issue : 
![collectionrefresh](https://user-images.githubusercontent.com/1583842/43198034-db284270-9015-11e8-9702-272378df0b4b.gif)

**Comment by bobsilverberg** [comment]
It looks like we need to invalidate the collection after adding an add-on to it in order for the Collection component to re-retrieve it. This is not a new bug and has likely existed since we implemented the Collections feature, but it should be fixed.

**Comment by bobsilverberg** [comment]
Thank you @dev-drprasad. This has not been marked as a "good first bug", but if you feel confident tackling it please feel free to do so.

**Comment by dev-drprasad** [comment]
@bobsilverberg I need some help. Once addon is added, we are dispatching `ADDON_ADDED_TO_COLLECTION` action. we don't have any collection update logic inside relevant reducer. should i change the reducer to update `collections` prop in state or dispatch new action like `GET_USER_COLLECTIONS` to update `collections` prop ???

**Comment by bobsilverberg** [comment]
@dev-drprasad I'm sorry I took so long to get back to you. I somehow didn't see the notification of this comment and only noticed it now.

You'll see we already have an action called [`UNLOAD_COLLECTION_BY_SLUG`](https://github.com/mozilla/addons-frontend/blob/41475137c7b45f6863309fe919d2f17b007ca8e3/src/amo/reducers/collections.js#L1306-L1316), so that's the logic we want to re-use in the case that an add-on is either added to or removed from a collection.

We also have actions for [`ADDON_ADDED_TO_COLLECTION`](https://github.com/mozilla/addons-frontend/blob/41475137c7b45f6863309fe919d2f17b007ca8e3/src/amo/reducers/collections.js#L1231-L1260) and [`ADDON_REMOVED_FROM_COLLECTION`](https://github.com/mozilla/addons-frontend/blob/41475137c7b45f6863309fe919d2f17b007ca8e3/src/amo/reducers/collections.js#L1332-L1337), so it's during the processing of those actions that we should invalidate the collection by reusing the logic from `UNLOAD_COLLECTION_BY_SLUG`.

Because that logic will now be needed in three places, I suggest extracting it into its own function, similar with what's being done for [`unloadUserCollections`](https://github.com/mozilla/addons-frontend/blob/41475137c7b45f6863309fe919d2f17b007ca8e3/src/amo/reducers/collections.js#L930-L954).

Please let me know if you have any questions about the above.

**Comment by motiko** [comment]
@bobsilverberg It looks like just dispatching UNLOAD_COLLECTION_BY_SLUG doesn't solve the problem as CollectionList component only dispatches fetchUserCollections [when there are no collections at all](https://github.com/mozilla/addons-frontend/blob/23bd311793001f8335137537583b6b64cb2de354/src/amo/pages/CollectionList/index.js#L49).  
Unless I'm missing something.   
  
Possible solution is to dispatch fetchUserCollections after collection is added in case not [editing](https://github.com/mozilla/addons-frontend/blob/23bd311793001f8335137537583b6b64cb2de354/src/amo/sagas/collections.js#L182). 
  
I can open a PR if this solution is acceptable.

**Comment by AlexandraMoga** [comment]
Still reproducing.
